#cloud-config
users:
  - name: ubuntu #username
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo-Regeln für diesen Benutzer
    groups: users, admin #Fügt den Benutzer "ubuntu" zu den Gruppen "users" und "admin" hinzu
    home: /home/ubuntu #Setzt das Homeverzeichnis des Benutzers auf
    shell: /bin/bash #Legt die Standard-Shell für den Benutzer auf /bin/bash fest
    ssh_authorized_keys: #Erlaubt die Festlegung von SSH-Schlüsseln für den Benutzer. In diesem Fall wird ein SSH-Schlüssel angegeben.
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI07wMGpDGKeLzZ+K8MEiEIbQHkLM9ygplmtt0KNsTFOjF2Id1O488V1BGAJDfLVXaGdfRf5MRdoWbn2vfR49/U7eNsD5Elk3T+NiM+Nq2WNiHJ9i95W6jJzYO7WEFzPJfpbFJM5oi3LiCyjMWhZ+AtEMS9mRqgZ3EEhX4yK2qkMp7Tp2A5F6PeWpQLicoxSRuO5qgsEGjSXxvfFue4A5sknqZFez+h6Yamy8IYnd9gYI8NlphvpXc2y8NaWfVLeZYndx4Wv7Cw51cqhW07vpsAiIX/HVXmwdXyFDvsjvWxVNAqKx+VHiHoT4Y8gA9lfty3xkIVqW0yRacZV3qC8NP aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false
disable_root: false
package_update: true
write_files:
  - path: /var/www/html/db.php
    content: |
      <?php
        //database
        $servername = "172.31.24.110";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";
        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }
        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
      ?>
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
